version: '3'
services:
  db:
    image: postgres
    container_name: db
    env_file: .env
  web:
    build: .
    container_name: webapp
    command: bundle exec "rm -f tmp/pids/server.pid && bundle install && rails s -b 0.0.0.0"
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/webapp
    links:
      - db
